### ISSUE TITLE
JSONFeedAuhtor

### ISSUE THREAD

**Issue by jhersh** [totocaster/JSONFeed#4]
Congrats, this is super neat! There's just one thing I'd change.

Yours truly,
a [`JSONFeedAuhtor`](https://github.com/totocaster/JSONFeed/blob/master/Classes/JSONFeedAuthor.swift#L11)

**Comment by totocaster** [comment]
Hah! More than dozen of eyeballs (including mine) couldn't see that. Thanks @jhersh !
